### ISSUE TITLE
Add ChannelSearchKind loader override support

### ISSUE THREAD

**Issue by david-risney** [david-risney/WebView2Utilities#73] opened 2024-02-26 19:11 UTC
Add support for the new loader override options documented by [ICoreWebView2ExperimentalEnvironmentOptions](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalenvironmentoptions?view=webview2-1.0.2415-prerelease). 

# ChannelSearchKind

Channel search kind currently only lets you reverse the order of searching. This is just like the existing reverse order loader override checkbox we have. But we want to also support this if its set by some outside script or something. We can continue to have one bool to represent if search order is reversed but when reading/writing to env var/reg we should check both the old location and this new one. 

When reading, if one is set and not the other or if they are both set but to different values, which one wins? Check that and match it when setting our bool.

When writing, write both locations. This will ensure that we support old loaders that don't have the new behavior.

registry key: ChannelSearchKind 
environment variable: WEBVIEW2_CHANNEL_SEARCH_KIND. 

Set the value to 1 to reverse search order.

**Comment by vickiez** [comment] 2024-03-15 17:54
Dupe of #78

**Closed by vickiez** 2024-03-15 17:54 UTC
Labels: enhancement
